# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent
RUN sed -i "s/#ServerName.*/ServerName 0.0.0.0:8080/g" /etc/httpd/conf/httpd.conf
RUN sed -i "s/^Listen.*/Listen 8080/g" /etc/httpd/conf/httpd.conf
RUN chgrp -R 0 /var/run/http* /var/log/http*
RUN chmod -R g=u /var/log/http* /var/log/http*
EXPOSE 8080
USER 1001
